doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '12.1'
        types:
            todo_list_identifier: 'Todo\Todo\Infrastructure\Storage\Doctrine\Type\TodoList\IdentifierType'
            todo_list_name: 'Todo\Todo\Infrastructure\Storage\Doctrine\Type\TodoList\NameType'
            task_identifier: 'Todo\Todo\Infrastructure\Storage\Doctrine\Type\TodoList\Task\IdentifierType'
            task_name: 'Todo\Todo\Infrastructure\Storage\Doctrine\Type\TodoList\Task\NameType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
