version: '3.4'

services:
  php:
    image: 'todo/dev/php:7.4'
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      COMPOSER_HOME: '/var/www/.composer'
      PHP_IDE_CONFIG: 'serverName=todo-cli'
      XDEBUG_ENABLED: '${XDEBUG_ENABLED:-0}'
      XDEBUG_CONFIG: 'remote_host=${REMOTE_HOST:-172.17.0.1}'
      BLACKFIRE_CLIENT_ID: '${BLACKFIRE_CLIENT_ID:-client_id}'
      BLACKFIRE_CLIENT_TOKEN: '${BLACKFIRE_CLIENT_TOKEN:-client_token}'
    volumes:
      - './.git:/srv/.git'
      - './back:/srv/todo'
      - './features:/srv/features'
      - '${HOST_COMPOSER_HOME:-~/.composer}:/var/www/.composer'
    working_dir: '/srv/todo'
    command: 'php'
    networks:
      - 'todo'

  fpm:
    image: 'todo/dev/php:7.4'
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      PHP_IDE_CONFIG: 'serverName=todo'
      XDEBUG_ENABLED: '${XDEBUG_ENABLED:-0}'
      XDEBUG_CONFIG: 'remote_host=${REMOTE_HOST:-172.17.0.1}'
      BLACKFIRE_CLIENT_ID: '${BLACKFIRE_CLIENT_ID:-client_id}'
      BLACKFIRE_CLIENT_TOKEN: '${BLACKFIRE_CLIENT_TOKEN:-client_token}'
    volumes:
      - './back:/srv/todo:rw'
    working_dir: '/srv/todo'
    command: 'php-fpm -F'
    networks:
      - 'todo'

  httpd-back:
    image: 'httpd:2.4'
    environment:
      APP_ENV: '${APP_ENV:-prod}'
    depends_on:
      - 'fpm'
    ports:
      - '${DOCKER_PORT_HTTP:-8002}:80'
    volumes:
      - './back:/srv/todo:ro'
      - './infra/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro'
      - './infra/httpd/back.conf:/usr/local/apache2/conf/vhost.conf:ro'
    networks:
      - 'todo'

  blackfire:
    image: blackfire/blackfire
    environment:
      BLACKFIRE_SERVER_ID: '${BLACKFIRE_SERVER_ID:-server_id}'
      BLACKFIRE_SERVER_TOKEN: '${BLACKFIRE_SERVER_TOKEN:-server_token}'
    networks:
      - 'todo'

networks:
  todo:

